name: oneverse
description: "Listen & Download the Holy Quran, one verse at a time."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Networking
  dio: ^5.3.3

  # State Management
  provider: ^6.0.5

  # Audio
  just_audio: ^0.9.35
  path_provider: ^2.1.1
  permission_handler: ^11.0.1


  # Local Storage
  shared_preferences: ^2.2.2

  # Other Utilities
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.14
  google_nav_bar: ^5.0.7
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs1 Ver18.ttf
  assets:
    - assets/images/logo.png

flutter_native_splash:
  color: "#ffffff" # Background color (aap dark bhi kar sakte hain #064e3b)
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  # Agar logo chota nazar aaye to ye line add karein:
  adaptive_icon_background: "#064E3B" # Wahi Emerald Green color
  adaptive_icon_foreground: "assets/images/logo.png"